%% Casos de uso (alto nivel)
flowchart TD
actorAnon[(Actor: Visitante anónimo)]
actorCliente[(Actor: Cliente)]
actorOrganizador[(Actor: Organizador)]
actorAdmin[(Actor: Admin)]

UC1[Explorar catálogo]
UC2[Registrarse]
UC3[Iniciar sesión]
UC4[Comprar tiquete]
UC5[Crear paquete deluxe]
UC6[Ver mis tiquetes]
UC7[Transferir tiquete]
UC8[Recargar saldo]
UC9[Proponer venue]
UC10[Crear evento]
UC11[Crear localidad]
UC12[Cargar asientos]
UC13[Crear oferta]
UC14[Aprobar/Rechazar venue]

actorAnon --> UC1
actorAnon --> UC2
actorAnon --> UC3

actorCliente --> UC1
actorCliente --> UC4
actorCliente --> UC5
actorCliente --> UC6
actorCliente --> UC7
actorCliente --> UC8

actorOrganizador --> UC9
actorOrganizador --> UC10
actorOrganizador --> UC11
actorOrganizador --> UC12
actorOrganizador --> UC13

actorAdmin --> UC14


