%% Diagrama de despliegue (ambientación local)
flowchart LR

subgraph Host[Host local]
  subgraph JVM[Proceso JVM]
    Main[Main]
    AppCli[CLI]
  end
  subgraph FS[Sistema de archivos CSV]
    usuarios[[usuarios.csv]]
    venues[[venues.csv]]
    eventos[[eventos.csv]]
    localidades[[localidades.csv]]
    asientos[[asientos.csv]]
    ofertas[[ofertas.csv]]
    tiquetes[[tiquetes.csv]]
    tAgregados[[tiquetes_agregados.csv]]
  end
end

Main --> AppCli
AppCli <--> usuarios
AppCli <--> venues
AppCli <--> eventos
AppCli <--> localidades
AppCli <--> asientos
AppCli <--> ofertas
AppCli <--> tiquetes
AppCli <--> tAgregados

note right of AppCli: Persistencia ligera basada en archivos CSV


