%% Secuencia: Transferencia de tiquete
sequenceDiagram
actor Cliente
participant AppCli
participant TransferService
participant TiqueteRepository

Cliente->>AppCli: transferirTiquete(ticketId, loginNuevo)
AppCli->>TiqueteRepository: findByComprador(cliente.id)
TiqueteRepository-->>AppCli: List<Tiquete>
AppCli-->>Cliente: Seleccionar tiquete
AppCli->>TransferService: transferir(cliente, ticketId, nuevoCompradorId)

TransferService->>TiqueteRepository: findById(ticketId)
TiqueteRepository-->>TransferService: Optional<Tiquete>
alt no existe o no es propietario
  TransferService-->>AppCli: BusinessException("Solo el propietario puede transferir")
else propietario válido
  TransferService->>Tiquete: transferirA(nuevoCompradorId)
  TransferService->>TiqueteRepository: update(Tiquete)
  TiqueteRepository-->>TransferService: OK
  TransferService-->>AppCli: OK
end


